documentReady(function(){
	magnifyingGlass();
	detail_menu();
	selected1('choose-color','item');
	selected2('choose-service','item-cat');
	selected2('choose-baitiao','item');
	buyAmount();
	recommendAd();
});